name = "cnr"
main = "src/index.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "CNR_CACHE", id = "83873a054dcb463eb2cf4283b2868fc1" }
]

[triggers]
crons = ["*/5 * * * *"]

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false